#!/usr/bin/env python3
"""
Repomix Parser - Extracts code components from repomix-summary.md

This module parses the compressed codebase representation generated by Repomix
and extracts structured information about code components (classes, methods,
interfaces, configurations, etc.) for use in documentation generation and
code analysis workflows.

Usage:
    # Default usage (reads from output/reports/repomix-summary.md)
    python repomix_parser.py

    # Custom input file
    python repomix_parser.py path/to/custom-repomix.md

    # Custom input and output files
    python repomix_parser.py path/to/input.md -o path/to/output.json

Module Usage:
    from repomix_parser import RepomixParser

    parser = RepomixParser("path/to/repomix-summary.md")
    if parser.load():
        components = parser.extract_all_components()
        parser.export_to_json("output.json")

Author: Framework Team
Version: 1.1.0
"""

import re
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, asdict


@dataclass
class CodeComponent:
    """
    Represents a code component found in the codebase.

    Attributes:
        name: The name of the component (e.g., class name, method name)
        type: The type of component (class, interface, method, config, enum, annotation)
        file_path: Path to the source file containing this component
        repomix_line: Line number in the repomix-summary.md file
        original_line: Line number in the original source file (if available)
        signature: Full signature of the component (e.g., method signature with parameters)
        parent_class: Name of the parent class (for methods and inner classes)
        snippet: Code snippet showing the component definition
    """
    name: str
    type: str  # class, interface, method, config, enum, annotation
    file_path: str
    repomix_line: int
    original_line: Optional[int] = None
    signature: Optional[str] = None
    parent_class: Optional[str] = None
    snippet: Optional[str] = None


class RepomixParser:
    """
    Parser for repomix-summary.md files generated by the Repomix tool.

    This class provides functionality to:
    1. Load and parse repomix-summary.md files
    2. Extract code components (classes, methods, interfaces, etc.)
    3. Map components to their source locations
    4. Export structured data for documentation and analysis

    Attributes:
        repomix_path: Path to the repomix-summary.md file
        content: List of lines from the loaded file
        file_boundaries: Dictionary mapping file paths to their line ranges
        components: Dictionary of extracted components organized by type
    """

    def __init__(self, repomix_path: str = "output/reports/repomix-summary.md"):
        """
        Initialize the RepomixParser.

        Args:
            repomix_path: Path to the repomix-summary.md file to parse.
                         Defaults to "output/reports/repomix-summary.md"
        """
        self.repomix_path = Path(repomix_path)
        self.content: List[str] = []
        self.file_boundaries: Dict[str, Tuple[int, int]] = {}

        # Initialize component storage by type
        self.components: Dict[str, List[CodeComponent]] = {
            'classes': [],      # Class definitions
            'interfaces': [],   # Interface definitions
            'methods': [],      # Methods and functions
            'enums': [],        # Enum definitions
            'configs': [],      # Configuration entries
            'annotations': [],  # Annotations and decorators
            'api_endpoints': [] # API endpoint definitions
        }

    def load(self) -> bool:
        """
        Load the repomix file into memory.

        Returns:
            bool: True if file loaded successfully, False otherwise
        """
        if not self.repomix_path.exists():
            print(f"❌ Repomix file not found: {self.repomix_path}")
            return False

        with open(self.repomix_path, 'r', encoding='utf-8') as f:
            self.content = f.readlines()

        print(f"✅ Loaded {len(self.content)} lines from {self.repomix_path}")
        self._identify_file_boundaries()
        return True

    def _identify_file_boundaries(self):
        """
        Identify where each file starts and ends in the repomix summary.

        This method scans through the content to find file boundaries marked
        by "## File: " headers and creates a mapping of file paths to their
        line ranges in the repomix file.
        """
        current_file = None
        start_line = 0

        for i, line in enumerate(self.content):
            # Check for file header marker
            if line.startswith("## File: "):
                if current_file:
                    # Save previous file boundary
                    self.file_boundaries[current_file] = (start_line, i - 1)

                # Start new file
                current_file = line[9:].strip()  # Remove "## File: " prefix
                start_line = i

        # Save last file boundary
        if current_file:
            self.file_boundaries[current_file] = (start_line, len(self.content) - 1)

        print(f"📁 Found {len(self.file_boundaries)} files in repomix summary")

    def extract_all_components(self) -> Dict:
        """
        Extract all code components from the repomix file.

        This method processes each file in the repomix summary and extracts
        various code components (classes, methods, interfaces, etc.) based
        on language-specific patterns.

        Returns:
            Dict: Dictionary containing lists of components organized by type
                  Keys: 'classes', 'interfaces', 'methods', 'enums', 'configs',
                        'annotations', 'api_endpoints'
        """
        # Process each file
        for file_path, (start, end) in self.file_boundaries.items():
            self._extract_from_file(file_path, start, end)

        # Print extraction summary
        total = sum(len(v) for v in self.components.values())
        print(f"\n📊 Extraction Summary:")
        print(f"  - Classes: {len(self.components['classes'])}")
        print(f"  - Interfaces: {len(self.components['interfaces'])}")
        print(f"  - Methods: {len(self.components['methods'])}")
        print(f"  - Enums: {len(self.components['enums'])}")
        print(f"  - Configs: {len(self.components['configs'])}")
        print(f"  - API Endpoints: {len(self.components['api_endpoints'])}")
        print(f"  - Total: {total} components")

        return self.components

    def _extract_from_file(self, file_path: str, start: int, end: int):
        """
        Extract components from a specific file section.

        Args:
            file_path: Path of the file being processed
            start: Starting line number in the repomix file
            end: Ending line number in the repomix file
        """
        # Skip non-code files
        if not self._is_code_file(file_path):
            return

        # Track current class for method association
        current_class = None
        in_code_block = False
        relative_line = 0

        for i in range(start, min(end + 1, len(self.content))):
            line = self.content[i]

            # Track code blocks
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                relative_line = 0
                continue

            if in_code_block:
                relative_line += 1

                # Java/C#/JSP/JSF patterns
                if file_path.endswith(('.java', '.cs')):
                    self._extract_java_components(line, file_path, i, relative_line, current_class)

                    # Track current class
                    class_match = re.match(r'\s*(public\s+)?(class|interface)\s+(\w+)', line)
                    if class_match:
                        current_class = class_match.group(3)

                # JSP/JSF patterns
                elif file_path.endswith(('.jsp', '.jsf', '.xhtml')):
                    self._extract_jsp_jsf_components(line, file_path, i, relative_line)
                    # Also try Java patterns since JSP can contain Java code
                    self._extract_java_components(line, file_path, i, relative_line, current_class)

                # Python patterns
                elif file_path.endswith('.py'):
                    self._extract_python_components(line, file_path, i, relative_line, current_class)

                    # Track current class
                    class_match = re.match(r'\s*class\s+(\w+)', line)
                    if class_match:
                        current_class = class_match.group(1)

                # JavaScript/TypeScript patterns
                elif file_path.endswith(('.js', '.ts', '.jsx', '.tsx')):
                    self._extract_javascript_components(line, file_path, i, relative_line)

                # Configuration files
                elif file_path.endswith(('.properties', '.yml', '.yaml', '.xml')):
                    self._extract_config_values(line, file_path, i, relative_line)

    def _is_code_file(self, file_path: str) -> bool:
        """
        Check if file is a code file we should parse.

        Args:
            file_path: Path to check

        Returns:
            bool: True if file should be parsed, False otherwise
        """
        code_extensions = (
            '.java', '.jsp', '.jsf', '.xhtml',  # Java and Java web files
            '.cs', '.aspx', '.ascx',  # .NET files
            '.py', '.js', '.ts', '.jsx', '.tsx',
            '.go', '.rb', '.php', '.swift', '.kt', '.scala', '.rs',
            '.cpp', '.c', '.h', '.hpp',
            '.properties', '.yml', '.yaml', '.xml'  # Configuration files
        )
        return file_path.endswith(code_extensions)

    def _extract_java_components(self, line: str, file_path: str, repomix_line: int,
                                 relative_line: int, current_class: Optional[str]):
        """
        Extract Java/C# specific components.

        Identifies classes, interfaces, enums, methods, and annotations
        from Java and C# code.

        Args:
            line: Current line of code
            file_path: Path to the source file
            repomix_line: Line number in repomix file
            relative_line: Line number in the code block
            current_class: Name of the current class context
        """

        # Classes and Interfaces
        class_match = re.match(r'\s*(public\s+|private\s+|protected\s+)?(abstract\s+)?(class|interface|enum)\s+(\w+)', line)
        if class_match:
            component_type = class_match.group(3)
            name = class_match.group(4)

            if component_type == 'enum':
                target = 'enums'
            elif component_type == 'interface':
                target = 'interfaces'
            else:
                target = 'classes'

            self.components[target].append(CodeComponent(
                name=name,
                type=component_type,
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                snippet=line.strip()
            ))

        # Methods
        method_match = re.match(r'\s*(public\s+|private\s+|protected\s+)?(static\s+)?([\w\[\]<>,\s]+)\s+(\w+)\s*\([^)]*\)', line)
        if method_match and not re.match(r'\s*(if|while|for|switch)\s*\(', line):
            return_type = method_match.group(3)
            method_name = method_match.group(4)

            # Skip constructors (same name as current class) and common keywords
            if method_name not in ['if', 'while', 'for', 'switch', 'catch'] and method_name != current_class:
                self.components['methods'].append(CodeComponent(
                    name=method_name,
                    type='method',
                    file_path=file_path,
                    repomix_line=repomix_line + 1,
                    original_line=relative_line,
                    signature=line.strip(),
                    parent_class=current_class,
                    snippet=line.strip()
                ))

        # Annotations (potential API endpoints)
        annotation_match = re.match(r'\s*@(\w+)(\([^)]*\))?', line)
        if annotation_match:
            annotation = annotation_match.group(1)
            if annotation in ['RequestMapping', 'GetMapping', 'PostMapping', 'PutMapping',
                            'DeleteMapping', 'Path', 'Route']:
                self.components['api_endpoints'].append(CodeComponent(
                    name=annotation,
                    type='api_endpoint',
                    file_path=file_path,
                    repomix_line=repomix_line + 1,
                    original_line=relative_line,
                    signature=line.strip(),
                    parent_class=current_class,
                    snippet=line.strip()
                ))

    def _extract_python_components(self, line: str, file_path: str, repomix_line: int,
                                  relative_line: int, current_class: Optional[str]):
        """
        Extract Python specific components.

        Identifies classes, functions, methods, and decorators from Python code.

        Args:
            line: Current line of code
            file_path: Path to the source file
            repomix_line: Line number in repomix file
            relative_line: Line number in the code block
            current_class: Name of the current class context
        """

        # Classes
        class_match = re.match(r'\s*class\s+(\w+)', line)
        if class_match:
            self.components['classes'].append(CodeComponent(
                name=class_match.group(1),
                type='class',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                snippet=line.strip()
            ))

        # Functions/Methods
        func_match = re.match(r'\s*def\s+(\w+)\s*\([^)]*\)', line)
        if func_match:
            self.components['methods'].append(CodeComponent(
                name=func_match.group(1),
                type='method' if current_class else 'function',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                parent_class=current_class,
                snippet=line.strip()
            ))

        # Decorators (potential API endpoints)
        decorator_match = re.match(r'\s*@(\w+\.)?(\w+)(\([^)]*\))?', line)
        if decorator_match:
            decorator = decorator_match.group(2)
            if decorator in ['route', 'get', 'post', 'put', 'delete', 'api', 'endpoint']:
                self.components['api_endpoints'].append(CodeComponent(
                    name=decorator,
                    type='api_endpoint',
                    file_path=file_path,
                    repomix_line=repomix_line + 1,
                    original_line=relative_line,
                    signature=line.strip(),
                    parent_class=current_class,
                    snippet=line.strip()
                ))

    def _extract_jsp_jsf_components(self, line: str, file_path: str, repomix_line: int,
                                    relative_line: int):
        """
        Extract JSP/JSF specific components and validations.

        Identifies JSP beans, scriptlets, JSF bindings, validators, and JSTL logic
        from JSP and JSF files.

        Args:
            line: Current line of code
            file_path: Path to the source file
            repomix_line: Line number in repomix file
            relative_line: Line number in the code block
        """

        # JSP useBean declarations (very common in JSP files)
        usebean_match = re.search(r'<jsp:useBean\s+id="(\w+)".*type="([^"]+)"', line)
        if usebean_match:
            bean_name = usebean_match.group(1)
            bean_type = usebean_match.group(2)
            # Extract just the class name from full path
            class_name = bean_type.split('.')[-1] if '.' in bean_type else bean_type

            self.components['classes'].append(CodeComponent(
                name=bean_name,
                type='jsp_bean',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=f"jsp:useBean {bean_name} of type {class_name}",
                snippet=line.strip()
            ))

        # JSP imports
        import_match = re.search(r'<%@\s*page.*import="([^"]+)"', line)
        if import_match:
            imports = import_match.group(1)
            # Track as configuration/import
            self.components['configs'].append(CodeComponent(
                name='jsp_import',
                type='import',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=f"JSP imports: {imports}",
                snippet=line.strip()
            ))

        # JSP Scriptlets with Java code
        scriptlet_match = re.search(r'<%[^@%].*%>', line)
        if scriptlet_match:
            # Mark as containing business logic
            self.components['methods'].append(CodeComponent(
                name='jsp_scriptlet',
                type='scriptlet',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature='JSP Scriptlet',
                snippet=line.strip()[:100]  # Limit snippet length
            ))

        # JSF Managed Beans
        bean_match = re.search(r'#\{(\w+)\.(\w+)', line)
        if bean_match:
            bean_name = bean_match.group(1)
            method_name = bean_match.group(2)

            # Add as method reference
            self.components['methods'].append(CodeComponent(
                name=method_name,
                type='jsf_binding',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                parent_class=bean_name,
                snippet=line.strip()
            ))

        # JSF Validators
        validator_match = re.search(r'<f:validate(\w+)', line)
        if validator_match:
            self.components['configs'].append(CodeComponent(
                name=f"JSF_{validator_match.group(1)}",
                type='jsf_validator',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                snippet=line.strip()
            ))

        # JSTL conditions (business logic)
        jstl_match = re.search(r'<c:(?:if|when|forEach|choose)', line)
        if jstl_match:
            self.components['configs'].append(CodeComponent(
                name=f"JSTL_{jstl_match.group(0)[3:]}",
                type='jstl_logic',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                snippet=line.strip()
            ))

    def _extract_javascript_components(self, line: str, file_path: str, repomix_line: int,
                                      relative_line: int):
        """
        Extract JavaScript/TypeScript components.

        Identifies classes, interfaces, functions, and methods from JS/TS code.

        Args:
            line: Current line of code
            file_path: Path to the source file
            repomix_line: Line number in repomix file
            relative_line: Line number in the code block
        """

        # Classes
        class_match = re.match(r'\s*(export\s+)?(class|interface)\s+(\w+)', line)
        if class_match:
            component_type = class_match.group(2)
            name = class_match.group(3)

            target = 'interfaces' if component_type == 'interface' else 'classes'
            self.components[target].append(CodeComponent(
                name=name,
                type=component_type,
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                snippet=line.strip()
            ))

        # Functions - regular function declarations
        func_decl_match = re.match(r'\s*(export\s+)?(async\s+)?function\s+(\w+)\s*\([^)]*\)', line)
        if func_decl_match:
            self.components['methods'].append(CodeComponent(
                name=func_decl_match.group(3),
                type='function',
                file_path=file_path,
                repomix_line=repomix_line + 1,
                original_line=relative_line,
                signature=line.strip(),
                snippet=line.strip()
            ))
        # Arrow functions and function expressions
        else:
            func_match = re.match(r'\s*(export\s+)?(const|let|var)\s+(\w+)\s*=\s*(async\s+)?(\([^)]*\)|function)', line)
            if func_match and func_match.group(3) not in ['if', 'while', 'for', 'switch']:
                self.components['methods'].append(CodeComponent(
                    name=func_match.group(3),
                    type='function',
                    file_path=file_path,
                    repomix_line=repomix_line + 1,
                    original_line=relative_line,
                    signature=line.strip(),
                    snippet=line.strip()
                ))
            # Object method syntax
            else:
                method_match = re.match(r'\s*(\w+)\s*:\s*(async\s+)?function\s*\([^)]*\)', line)
                if method_match:
                    self.components['methods'].append(CodeComponent(
                        name=method_match.group(1),
                        type='function',
                        file_path=file_path,
                        repomix_line=repomix_line + 1,
                        original_line=relative_line,
                        signature=line.strip(),
                        snippet=line.strip()
                    ))

    def _extract_config_values(self, line: str, file_path: str, repomix_line: int,
                              relative_line: int):
        """
        Extract configuration values.

        Identifies key-value pairs from properties, YAML, and other config files.

        Args:
            line: Current line of code
            file_path: Path to the source file
            repomix_line: Line number in repomix file
            relative_line: Line number in the code block
        """

        # Properties files
        if file_path.endswith('.properties'):
            config_match = re.match(r'([^#=\s]+)\s*=\s*(.+)', line)
            if config_match:
                self.components['configs'].append(CodeComponent(
                    name=config_match.group(1),
                    type='property',
                    file_path=file_path,
                    repomix_line=repomix_line + 1,
                    original_line=relative_line,
                    signature=line.strip(),
                    snippet=config_match.group(2).strip()
                ))

        # YAML files
        elif file_path.endswith(('.yml', '.yaml')):
            config_match = re.match(r'\s*([^:#]+):\s*(.+)', line)
            if config_match and not line.strip().startswith('#'):
                self.components['configs'].append(CodeComponent(
                    name=config_match.group(1).strip(),
                    type='yaml_config',
                    file_path=file_path,
                    repomix_line=repomix_line + 1,
                    original_line=relative_line,
                    signature=line.strip(),
                    snippet=config_match.group(2).strip()
                ))

    def export_to_json(self, output_path: str = "output/context/codebase-citations.json"):
        """
        Export extracted components to JSON file.

        The output JSON structure includes:
        - All extracted components organized by type
        - Metadata section for additional information

        Args:
            output_path: Path for the output JSON file.
                        Defaults to "output/context/codebase-citations.json"

        Returns:
            Dict: The exported data structure
        """
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        # Convert dataclasses to dictionaries for JSON serialization
        export_data = {}
        for key, components in self.components.items():
            export_data[key] = [asdict(c) for c in components]

        # Add metadata with basic statistics
        export_data["metadata"] = {
            "source_file": str(self.repomix_path),
            "total_components": sum(len(v) for v in self.components.values()),
            "file_count": len(self.file_boundaries)
        }

        # Write to JSON file
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(export_data, f, indent=2)

        print(f"✅ Exported citations to {output_file}")
        return export_data


if __name__ == "__main__":
    import argparse

    # Set up command-line argument parsing
    arg_parser = argparse.ArgumentParser(description='Parse repomix-summary.md file and extract code components')
    arg_parser.add_argument(
        'repomix_path',
        nargs='?',
        default='output/reports/repomix-summary.md',
        help='Path to the repomix-summary.md file (default: output/reports/repomix-summary.md)'
    )
    arg_parser.add_argument(
        '--output',
        '-o',
        default='output/context/codebase-citations.json',
        help='Output JSON file path (default: output/context/codebase-citations.json)'
    )

    args = arg_parser.parse_args()

    # Run the parser with provided or default path
    parser = RepomixParser(repomix_path=args.repomix_path)
    if parser.load():
        parser.extract_all_components()
        parser.export_to_json(output_path=args.output)